name: adminapp
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3
  stokvelibrary:
    path: ../../stellar-stokvel-repo/stokvelibrary/stokvelibrary


flutter_icons:
  ios: true
  android: true
  image_path_ios: "assets/logo.png"
  image_path_android: "assets/logo.png"
#  adaptive_icon_background: "assets/launcher/background.png"
#  adaptive_icon_foreground: "assets/launcher/foreground.png"
#  flutter packages pub run flutter_launcher_icons:main

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.7.0"

flutter:


  uses-material-design: true

  assets:
    - .env
    - download1.jpeg
    - download3.jpeg
    - download4.jpeg
    - download8.jpeg
    - images8.jpeg
    - images12.jpeg
    - images14.jpeg
    - images19.jpeg
    - images22.jpeg
    - images14.png
    - logo.png
    - logo_white.png

