name: stokvelibrary
description: Stokvel Library
version: 0.0.1
author:
homepage:

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  stellarplugin: ^0.0.3+3
  cloud_firestore: ^0.13.4
  firebase_auth: ^0.15.5+2
  firebase_storage: ^3.1.3
  intl: ^0.16.1
  shared_preferences: ^0.5.6+2
  flutter_dotenv: ^2.1.0
  permission_handler: ^4.4.0
  uuid: ^2.0.4
  provider: ^4.0.4
  dots_indicator: ^1.1.0
  google_fonts: ^0.3.9
  google_sign_in: ^4.1.4
  flutter_email_sender: ^2.2.2
  image_picker: ^0.6.3+4
#  flutter_launch: ^0.2.0
  contacts_service: ^0.3.10
  circular_profile_avatar: ^1.0.6
  autocomplete_textfield: ^1.7.3
  flutter_sms: ^2.0.0+2


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

